version: '3.4'

services:
  proyectomata20231:
    image: proyectomata20231
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
